title: Relaton
description: The interoperable data model for citations
# The above two are used by jekyll-seo-tag for things such as
# `<title>` and `<meta>` tags, as well as elsewhere by the theme.

url: https://www.relaton.com
github_repo_url: https://github.com/relaton/relaton.com

algolia_search:
  api_key: '31ca4bad475130bdaee582a0b9f40806'
  index_name: 'metanorma'

tagline: >-
  Interoperable data&nbsp;model for&nbsp;citations
  based&nbsp;on&nbsp;ISO&nbsp;690

landing_priority: [custom_intro, blog, specs, software]

relaton:
  supported_bibliographies:
    - id: iso
      label: ISO
      gem: relaton-iso
      sources:
        - { url: "https://www.iso.org/", label: "International Organization for Standardization" }
    - id: iec
      label: IEC
      gem: relaton-iec
      sources:
        - { url: "https://www.iec.ch/", label: "International Electrotechnical Commission" }
    - id: itu
      label: ITU
      gem: relaton-itu
      sources:
        - { url: "https://www.itu.int/", label: "International Telecommunication Union" }
    - id: ietf
      label: IETF (Internet Drafts, RFCs)
      gem: relaton-ietf
      sources:
        - { url: "http://xml2rfc.tools.ietf.org/", label: "IETF XML2RFC" }
    - id: nist
      label: NIST
      gem: relaton-nist
      sources:
        - { url: "https://nist.gov", label: "NIST.gov website" }
    - id: ogc
      label: OGC
      gem: relaton-ogc
      sources:
        - { url: "https://www.ogc.org/", label: "Open Geospatial Consortium" }
    - id: iev
      label: IEC Electropedia (IEV)
      gem: relaton-iev
      sources:
        - { url: "https://www.electropedia.org/", label: "IEC Electropedia" }
    - id: gb
      label: GB (Chinese national standards)
      gem: relaton-gb
      sources:
        - { label: "GB websites" }

author: "Ribose Inc."

authors:
  - name: Ribose Inc.
    email: open.source@ribose.com

contact_email: open.source@ribose.com

theme: jekyll-theme-open-project

parent_hub:
  git_repo_url: https://github.com/riboseinc/open.ribose.com
  home_url: https://open.ribose.com/

social:
  links:
    - https://twitter.com/RiboseUS
    - https://github.com/relaton/relaton

legal:
  name: Ribose Group Inc.
  tos_link: https://www.ribose.com/tos
  privacy_policy_link: https://www.ribose.com/privacy

home_calls_to_action:
  - { url: "/software/relaton/docs/README/", title: "Using the gem" }
  #- { url: "/software/relaton-cli/docs/README/", title: "Using the CLI" }

permalink: /blog/:month-:day-:year/:title/

plugins:
  - jekyll-assets
  - jekyll-seo-tag
  - jekyll-sitemap

tag_namespaces:
  software:
    writtenin: "Written in"
    bindingsfor: "Bindings for"
    user: "Target user"
    interface: "Interface"
  specs:
    audience: "Audience"
    completion_status: "Status"
